// <auto-generated />
using System;
using BikePartsTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BikePartsTracker.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260501133000_SwapRideDistanceColumnNames")]
    partial class SwapRideDistanceColumnNames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikePartsTracker.Models.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StravaBikeId")
                        .HasColumnType("text");

                    b.Property<double>("StravaDistance")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalDistance")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("BikePartsTracker.Models.BikePart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("HistoryJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("MileageAtInstallation")
                        .HasColumnType("double precision");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PartType")
                        .HasColumnType("integer");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer");

                    b.Property<double>("ScheduleValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("UserId");

                    b.ToTable("BikeParts");
                });

            modelBuilder.Entity("BikePartsTracker.Models.ChainCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveChainId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChainsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ChainsJson");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("IntervalKm")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.ToTable("ChainCycles");
                });

            modelBuilder.Entity("BikePartsTracker.Models.ExternalServiceIntegration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ServiceType")
                        .HasColumnType("integer");

                    b.Property<string>("ServiceUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ServiceType")
                        .IsUnique();

                    b.ToTable("ExternalServiceIntegrations");
                });

            modelBuilder.Entity("BikePartsTracker.Models.PartUsageHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BikePartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsShadow")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceUsagePeriodId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("SourceUsagePeriodId");

                    b.HasIndex("WorkId");

                    b.HasIndex("BikePartId", "StartDate", "EndDate");

                    b.ToTable("PartUsageHistories");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Ride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BikeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<double>("Distance")
                        .HasColumnType("double precision");

                    b.Property<string>("GearId")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("RecordedDistance")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("StartDateLocal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("StravaActivityId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("UserId", "StartDateLocal");

                    b.HasIndex("UserId", "StravaActivityId")
                        .IsUnique()
                        .HasFilter("\"StravaActivityId\" IS NOT NULL");

                    b.ToTable("Rides");
                });

            modelBuilder.Entity("BikePartsTracker.Models.StravaAthlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<Guid>("IntegrationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<long>("StravaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IntegrationId")
                        .IsUnique();

                    b.ToTable("StravaAthletes");
                });

            modelBuilder.Entity("BikePartsTracker.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BikePartsTracker.Models.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DefaultChainCycleIntervalKm")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultChainCycleLength")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("defaultUseChainCycle")
                        .HasColumnType("boolean");

                    b.Property<bool>("showTips")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ParentType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ParentType", "ParentId", "IsActive");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Bike", b =>
                {
                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithMany("Bikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.BikePart", b =>
                {
                    b.HasOne("BikePartsTracker.Models.Bike", "Bike")
                        .WithMany("Parts")
                        .HasForeignKey("BikeId");

                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithMany("Parts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.ChainCycle", b =>
                {
                    b.HasOne("BikePartsTracker.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");
                });

            modelBuilder.Entity("BikePartsTracker.Models.ExternalServiceIntegration", b =>
                {
                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithMany("ExternalServiceIntegrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.PartUsageHistory", b =>
                {
                    b.HasOne("BikePartsTracker.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikePartsTracker.Models.BikePart", "BikePart")
                        .WithMany("UsageHistory")
                        .HasForeignKey("BikePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BikePartsTracker.Models.PartUsageHistory", "SourceUsagePeriod")
                        .WithMany("ShadowChildren")
                        .HasForeignKey("SourceUsagePeriodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikePartsTracker.Models.Work", "Work")
                        .WithMany("ShadowUsagePeriods")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Bike");

                    b.Navigation("BikePart");

                    b.Navigation("SourceUsagePeriod");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Ride", b =>
                {
                    b.HasOne("BikePartsTracker.Models.Bike", "Bike")
                        .WithMany("Rides")
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithMany("Rides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.StravaAthlete", b =>
                {
                    b.HasOne("BikePartsTracker.Models.ExternalServiceIntegration", "Integration")
                        .WithOne("StravaAthlete")
                        .HasForeignKey("BikePartsTracker.Models.StravaAthlete", "IntegrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Integration");
                });

            modelBuilder.Entity("BikePartsTracker.Models.UserSettings", b =>
                {
                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("BikePartsTracker.Models.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Work", b =>
                {
                    b.HasOne("BikePartsTracker.Models.User", "User")
                        .WithMany("Works")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Bike", b =>
                {
                    b.Navigation("Parts");

                    b.Navigation("Rides");
                });

            modelBuilder.Entity("BikePartsTracker.Models.BikePart", b =>
                {
                    b.Navigation("UsageHistory");
                });

            modelBuilder.Entity("BikePartsTracker.Models.ExternalServiceIntegration", b =>
                {
                    b.Navigation("StravaAthlete");
                });

            modelBuilder.Entity("BikePartsTracker.Models.PartUsageHistory", b =>
                {
                    b.Navigation("ShadowChildren");
                });

            modelBuilder.Entity("BikePartsTracker.Models.User", b =>
                {
                    b.Navigation("Bikes");

                    b.Navigation("ExternalServiceIntegrations");

                    b.Navigation("Parts");

                    b.Navigation("Rides");

                    b.Navigation("Settings");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("BikePartsTracker.Models.Work", b =>
                {
                    b.Navigation("ShadowUsagePeriods");
                });
#pragma warning restore 612, 618
        }
    }
}
